### ISSUE TITLE
feat: add our mission section

### ISSUE THREAD

**Issue by Anyr00d** [cyscomvit/cyscom-website#14]
# Add Our Mission Section

## Overview
The website's landing page currently lacks a dedicated Our Mission section that highlights the chapter's core values and purpose. This issue involves adding the Our Mission section to the landing page based on the provided Figma design, using Tailwind CSS for styling and layout.

## Task
Implement the Our Mission section with the following requirements:
- Ensure the design closely follows the Figma file, maintaining visual consistency with the rest of the landing page.
- Utilize Tailwind CSS utility classes for layout, typography, and spacing.
- Ensure the section is fully responsive and looks good across all screen sizes.
- Avoid using inline styles unless necessary.

### Figma design
https://www.figma.com/design/Nzahg0BeYXdUECGXRzLKsP/CYSCOM-main-UI?node-id=0-1&t=RgHhWSuukMqKvkAm-1

**Note: Issues are limited only to Cyscom members**

**Comment by shivam1608** [comment]
hello, can you assign this issue to me?

**Comment by Ironpatriot06** [comment]
Hey, can you please assign this issue to me.

**Comment by ezhil56x** [comment]
Assigning @shivam1608 on fcfs basis
