### ISSUE TITLE
feat: add our journey section

### ISSUE THREAD

**Issue by Anyr00d** [cyscomvit/cyscom-website#15]
# Add Our Journey Section

## Overview
The website's landing page currently lacks a dedicated Our Journey section that highlights the chapter's milestones along our path. This issue involves adding the Our journey section to the landing page based on the provided Figma design, using Tailwind CSS for styling and layout.

## Task
Implement the Our Journey section with the following requirements:
- Ensure the design closely follows the Figma file, maintaining visual consistency with the rest of the landing page.
- Utilize Tailwind CSS utility classes for layout, typography, and spacing.
- Ensure the section is fully responsive and looks good across all screen sizes.
- Avoid using inline styles unless necessary.

### Figma design
https://www.figma.com/design/Nzahg0BeYXdUECGXRzLKsP/CYSCOM-main-UI?node-id=0-1&t=RgHhWSuukMqKvkAm-1

**Note: Issues are limited only to Cyscom members**

**Comment by Ironpatriot06** [comment]
Hey, can you assign this issue to me.
